Add barre separate and fix styling
francksefu/booksmr pull request #6
Opened 2023-06-16 21:22 UTC by francksefu

Add any missing JSX elements to your project (without adding extra functionality) -> done
Your final design should match Zeplin's design (this includes all elements + the same styling) -> done
You may use the CSS rules detailed in Zeplin to style the website. -> done

2023-06-16 22:11 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @francksefu  :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Descriptive pull request.
✔️ Follow the correct Git flow.
✔️ Application is working fine.

## Required Changes ♻️

- [ ] I can see the name of the project is given wrong in the `Readme`. It is not the leaderboard project. Kindly fix this issue to make it a professional readme.

![image](https://github.com/francksefu/booksmr/assets/60083437/52c488f0-4569-4753-82bf-650fe507385f)


***Please kindly check the comments/review below.***

## Optional suggestions 🤷‍♂️

- [ ] ***[OPTIONAL]***  I can see this is not your first pull request. It is recommended and must to do the same task within the same `PR` and not merge or close before the approval. If by mistake it is closed or merged before approval then we need to add the previous `PR` link with the new `PR`. Kindly remember it for future.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 22:11 UTC, Tufahel commented on src/components/BooksRender.jsx
> +      <BooksList />
- [ ] Inside `BooksList` component you have used `ul` and `li` which is correct. But by default `ul` and `li` always produce a `dot` before any `item`. I would recommend you use `no-style` CSS class to remove the `dot`. Kindly fix this issue. Consider going through this [content](https://gomakethings.com/creating-unstyled-lists/) for help.

- ![image](https://github.com/francksefu/booksmr/assets/60083437/67e4205c-f4c0-43dc-912d-c88e21e05996)

2023-06-16 22:11 UTC, Tufahel commented on src/App.css
> +  width: 100rem;
- [ ] I need to scroll from `left to right` to see the whole content. That means the whole content is not `fitting` within my browser interface. That shouldn't be the issue as per the given design. Kindly fix this issue.

![image](https://github.com/francksefu/booksmr/assets/60083437/bbf62527-f753-41b3-a217-c6607334acd3)

2023-06-16 23:00 UTC, alexander16108 requested changes
Hi @francksefu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/wsUuw16j6oyxLLRnnK/giphy.gif"/>

## Highlights
✔️ Descriptive pull request.
✔️ Follow the correct Git flow.
✔️ Application is working fine.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 23:00 UTC, alexander16108 commented on src/components/BooksRender.jsx
> +      <BooksList />
good job on removing the scroll on the webpage but that doesn't solve the problem of the whole content not fitting within my browser interface. please fix this and try again 

![image](https://github.com/francksefu/booksmr/assets/60612329/ebb492bb-da87-4966-bbd6-0b5f53c0aa71)

2023-06-17 00:20 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @francksefu, 👋 👋 

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous revieer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️
- Styling of the bookstore CMS project ✔️
- Zeplin Design template used for the design ✔️
- There is good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 13:32 UTC, merged